# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rfay1n70tJ1NMRiAfXkJ2sdqiPagPZl8
"""

def lower_triangular(n):
    print("Lower Triangular Pattern:")
    for i in range(1, n + 1):
        print("* " * i)
    print()

def upper_triangular(n):
    print("Upper Triangular Pattern:")
    for i in range(n, 0, -1):
        spaces = "  " * (n - i)
        stars = "* " * i
        print(spaces + stars)
    print()

def pyramid(n):
    print("Pyramid Pattern:")
    for i in range(1, n + 1):
        spaces = " " * (n - i)
        stars = "* " * i
        print(spaces + stars)
    print()

rows = 5

lower_triangular(rows)
upper_triangular(rows)
pyramid(rows)

